package Exception_;

public class test1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
try {
	int a=5/0;
}
catch(Exception e) {
	System.out.println("An error occured");
}
finally {
	System.out.println("Here the programs comes to end");
}
	}

}
